### ISSUE TITLE
Can you compile and release it even as beta?

### ISSUE THREAD

**Issue by regener** [SamVanheer/BSPViewer#1]
It would take a really long time for me to get this compiled since I don't know much about how that works, so can I ask for a compiled release?

**Comment by SamVanheer** [comment]
This is just a prototype, if you want a complete viewer i suggest you use [Crafty](http://nemesis.thewavelength.net/index.php?p=45)

I will eventually use [SharpLife's](https://github.com/SamVanheer/SharpLife-Engine) code to make a BSP viewer, but that will take some time since its renderer is unfinished.

**Comment by regener** [comment]
I see, will give it a try.
Thank you
